name: Check Dependencies

on:
  push:
    branches:
      - main

jobs:
  check_dependencies:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7.16', '3.8.16', '3.9.16', '3.10.11', '3.11.1', '3.11.2', '3.11.3']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Setup files
          uses: actions/checkout@v3

        - name: Setup Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'

        - name: Upgrade pip
          run: pip install --upgrade pip

        - name: Install pip-tools
          run: pip install pip-tools

        - name: Run pip-compile
          run: if [ -f requirements.in ]; then pip-compile --resolver=backtracking; fi

        - name: Install dependencies
          run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Rename requirements.txt
          run: mv requirements.txt requirements_${{ matrix.os }}_${{ matrix.python-version }}.txt

        - name: Brownie version
          run: brownie --version

        - name: Upload requirements.txt
          uses: actions/upload-artifact@v3
          with:
            name: requirements_${{ matrix.os }}_${{ matrix.python-version }}
            path: requirements_${{ matrix.os }}_${{ matrix.python-version }}.txt
